### ISSUE TITLE
Fullerite collectors need to be killed after their collection interval is exceeded

### ISSUE THREAD

**Issue by tsheasha** [Yelp/fullerite#125]
Fullerite go collectors are not terminated if their collection times expire, like diamond does. This means if a collector can run forever which really puts a lot of stress on resources and can cause memory to grow a lot as well.

**Comment by tiras-j** [comment]
@tsheasha I might be mistaken but don't the collectors run sequentially but inside their own goroutines, instead of the way diamond exec's each collector separately on each collection run. So that if a given collector takes too long to run we don't actually spawn a new one, it just doesn't get data out at the proper interval. Also it looks like the collector goroutine is an infinite loop of sequential:
```
Collect()
Sleep(duration)
```
So that we don't actually run once every interval but rather we wait one interval between runs. Not sure if this is what we want.

**Comment by tsheasha** [comment]
@tiras-j collectors are instantiated sequentially yes however each collector after instantiated runs in its own go routine in which the collector calls Collect infinitely in between time.Sleep of the collector's specific interval if collection. This is exactly the same as what dianond does. In both diamond and fullerite we *never* EVER spawn a new instance of the collector.

**Comment by gnufied** [comment]
If a collector is indeed stuck in `Collect` call for long time, why are we assuming that - it is going to  put lot of stress on resources? For all we know, it might be stuck on some IO. It can also be attempting to connect to an external socket. None of the above imply that collector is taking lot of resources. It is simply stuck on some sort of IO.

We have to be bit careful here.

**Comment by tsheasha** [comment]
We always assume worst case in which the collector is usung a lot of memory and CPU and not stuck on IO. If it is however stuck on IO it also is a good reason to kill it and try again.

I am not sure why you are assuming it is an IO issue ... My solution is tackling a more broader issue where collectors run for linger than they should "period". Whether that is IO stuck or even deadlocked is not really a controlling factore here. We could risk the chance of abusing resources.

**Comment by tsheasha** [comment]
@tiras-j Some useful discussions on killing a go routine:
https://groups.google.com/forum/#!topic/golang-nuts/SPAgm0TlWc0/discussion
https://groups.google.com/forum/#!topic/golang-nuts/y4h_00veKHU/discussion

It is basically impossible to do so. However that does not mean was cona't fix our issue. It just means we can't fix it by killing a go routine.

**Comment by tsheasha** [comment]
@tiras-j small update using defer panic and recover works perfectly for all scenarios that are not ours. Since we want to run collect() in the same processing thread it is impossible to stop it's execution on a timer running out I have been trying to hack around it using defer, recover and panic all day.

I have however thought another idea, let me see what I can do with it.

**Comment by tsheasha** [comment]
@tiras-j This is my current progress: https://github.com/tsheasha/fullerite/commit/26174cdde8fd1a5d49abd8eab3759e44b5d22ba4
It is incomplete and doesn't do *exactly* what we want but I am iterating over it to get it to do what we want.
