### ISSUE TITLE
disconnected operation / backlog ability?

### ISSUE THREAD

**Issue by KlavsKlavsen** [Yelp/fullerite#131]
Can fullerite "keep stats" on-disk or in-memory - if the backend (graphite) server isn't responding for f.ex. 15 minutes ? Its one feature that diamond currently does not have, which I'd really like, and figured you might have designed in? :)

**Comment by tsheasha** [comment]
@KlavsKlavsen fullerite does not currently support this buffering behaviour. If a backend is unreachable the current points in line to be emitted will be dropped as can be seen from the behaviour of the SignalFx handler for example: https://github.com/Yelp/fullerite/blob/master/src/fullerite/handler/signalfx.go#L152-L156

This it is very dangerous to do for a couple of reasons:-
* you risk an increase in memory that can affect the applications running on the host
* When your backend does come back up, it will be hammered with a large number of metrics that might cause it to go down again.

This is not to say this behaviour can not be implemented. I am pointing out that if it is implemented users will have to be very careful with using it and it feels like one of those features that if added will be a constant source of issues.

I am open to suggestions for how you think this can be implemented in a way that addresses the aforementioned issues.

**Comment by zachm** [comment]
It seems like this wouldn't be hard to implement, but we'd need to be very careful with the issues that @tsheasha mentioned. As for memory usage, we could set that up as a circular buffer, limits on time to keep metrics, limits on bytes of metric data, or both, and make them configurable at the application level.

As for hammering the backend, we'd have to carefully throttle the send rate for most backends. Plus, some of the supported handlers (definitely SignalFx, perhaps Datadog as well) do not support sending old datapoints to the ingest API. For those, we'd need explicit backfill support as well.

I guess my feeling, @KlavsKlavsen, is that if you can implement this in a safe manner, feel free to send us a PR. Uncertain as to whether it's worth your time though, are gaps in your monitoring that important? Or does you backend go down that frequently? If so you might address that first :)

**Comment by KlavsKlavsen** [comment]
Well sometimes a server can't reach our graphite server (either graphite is shortly down - or the network between is) - and then it would be nice if those holes, got filled out when link came back.. :)

So no.. its not terribly important.. IMHO nice to have though.
