### ISSUE TITLE
Reuse handler connection

### ISSUE THREAD

**Issue by ChristianKniep** [Yelp/fullerite#235]
What is the best way to reuse a handler connection?

The current handlers (e.g. Graphite) is connecting each time metrics are emitted.
I would like to establish this connection once and reuse it at the individual commit.

Maybe within `Configure`?

**Comment by gnufied** [comment]
`Signalfx` handler uses - https://github.com/Yelp/fullerite/blob/master/src/fullerite/util/http_alive.go type  for http connections. This type implements `Keep-Alive` with good defaults. 

You can perhaps use this type for same effect.
