### ISSUE TITLE
the handlers should have a timer that triggers on its interval

### ISSUE THREAD

**Issue by squirrely** [Yelp/fullerite#24]
When a single collector (or small set of them) are enabled, the number of calls to the handler.Handle are too low to happen constantly. This means that the handler doesn't check if it's interval has expired. This causes the emitted metrics to be 20 seconds apart instead of the 10 seconds.

**Comment by ericchu94** [comment]
I think this can be solved easily using https://gobyexample.com/timeouts

**Comment by ericchu94** [comment]
Maybe tickers is a better choice https://gobyexample.com/tickers
