### ISSUE TITLE
Make fails 

### ISSUE THREAD

**Issue by gamer22026** [Yelp/fullerite#279]
The package github.com/davecheney/profile was removed as of 7-26-2016 resulting in make failure:

warning: "github.com/davecheney/profile/..." matched no packages

See https://github.com/davecheney/profile/commit/3b20dcd2e3724478e3614c109eb186ba6c4f8fe1

**Comment by sagar8192** [comment]
+1

**Comment by poros** [comment]
This is going to be fixed in #280

**Comment by dichiarafrancesco** [comment]
should be fixed now! closing this.
