### ISSUE TITLE
Zookeeper diamond collector's limit_maxconn is completely broken. Let's remove it.

### ISSUE THREAD

**Issue by tub** [Yelp/fullerite#350]
We've recently upped the log level of the zookeeper collector which has exposed an issue that has always existed in the collector. We're trying to find the connection limit from the command line args, but we don't have the PID to start with.

Let's just get rid of the code, it hasn't been working since we first imported it.

**Comment by poros** [comment]
I have no idea of how this feature works, but on the fullerite side this is fine.If you want someone else expert in zookeeper looking at this call them in, otherwise go for it!
