### ISSUE TITLE
Build fails on go 1.11

### ISSUE THREAD

**Issue by drolando** [Yelp/fullerite#385]
```
Testing fullerite
# fullerite/vendor/github.com/samuel/go-thrift/examples/scribe
src/fullerite/vendor/github.com/samuel/go-thrift/examples/scribe/thrift.go:63:9: e declared and not used
FAIL    fullerite [build failed]
Makefile:72: recipe for target 'fullerite-tests' failed
```

go-thrift fails in the exactly same way in travis: https://travis-ci.org/samuel/go-thrift/jobs/496310305.
That library isn't actively supported though. We can try to send a PR to fix that bug or just use the default apache thrift library and write the scribe client ourselves which shouldn't be too difficult.

**Comment by vkhromov** [comment]
@drolando, Fullerite has been migrated to 1.13 in #402, I believe it should be fine with 1.11 as well?
