### ISSUE TITLE
Extend ProcStatus collector for other metrics

### ISSUE THREAD

**Issue by yalinhuang** [Yelp/fullerite#54]
It'd be great to get other system-level metrics per process, e.g., CPU time, socket statistics.

**Comment by ericchu94** [comment]
CPUTime is now collected as of 2c75723894efa839a4c658e210c510fb42fec386

**Comment by tsheasha** [comment]
@smallredbean is there a list of metrics you would like to have through proc-status? It would be great if you can add that here so I can work on getting them for you.
