### ISSUE TITLE
Extend ProcStatus collector to configure customized dimensions by exposing PID

### ISSUE THREAD

**Issue by smallredbean** [Yelp/fullerite#55]
We are looking at adding customized dimensions for the application processes that have specially-formatted "cmdline". The "cmdline" acts as an interface for the application to "talk" to ProcStatus to add more info to tag onto the proc statistics. 

Instead of hard binding on "cmdline", we can make it more generic by exposing PID to the configuration. In other words, users add a shell script to the configuration assuming PID is given; ProcStatus runs the command to derive the values of the customized dimensions.

An example config can be
```
{
....
"collectors": {
  "ProcStatus": {
    generatedDimensions:{
      "stream": "ps aux | grep %{PID}% | cut -d \" \"",
      "somethingelse": "....."
    }
  },
},
```

Super thx @squirrely for the idea :)

**Comment by baris** [comment]
Closed by #61.
