### ISSUE TITLE
Update upstream libraries in make process

### ISSUE THREAD

**Issue by tsheasha** [Yelp/fullerite#93]
Some upstream libraries get updated and since we use them we need to be up to date with their latest versions so we can utilise their new features.

Otherwise if we try to use a new feature and make it work locally *due to a new installation of fullerite* with a clean on-disk cache of libraries, we get the errors similar to 
Getting dependencies...

fullerite/collector
src/fullerite/collector/procstatus_linux.go:73: proc.Comm undefined (type procfs.Proc has no field or method Comm):

Keeping in mind that proc.Comm is defined in the latest version of that library and we already use it in fullerite since the developer in charge of it had the latest version of that library installed by mere coincidence since they started on a clean fullerite installation.

**Comment by gnufied** [comment]
i think it is worth exploring one of those go package managers going forward. The out of box package management doesn't provide us a way to lock down version of a package.

**Comment by gnufied** [comment]
Most mature solution looks like - https://github.com/tools/godep

**Comment by tsheasha** [comment]
Thanks for the heads up @gnufied I have started on METRICS-96 and will explore more options as well.

**Comment by gnufied** [comment]
This is fixed in master.
